### ISSUE TITLE
Scheduled bans executed too early

### ISSUE THREAD

**Issue by HeadTriXz** [HeadTriXz/Barry#107]
It appears that there is a minor issue with the SQL query responsible for retrieving expired scheduled bans in the DWCScheduledBanRepository.ts file. The query seems to be in the wrong order, leading to unintended behaviour. To maintain the contributor's dignity, we won't mention their name or highlight this as a bug. In fact, let's all pretend this never happened.

https://github.com/HeadTriXz/Barry/blob/fe5f499ab665d84431fd3de34952a7ea46757da3/apps/barry/src/modules/moderation/database/DWCScheduledBanRepository.ts#L105

> **Note**
> Luckily, only one person has been affected by this issue.

**Comment by KeyboardRage** [comment]
> Scheduled bans executed too early
That's an eloquent way to word instant ban

**Comment by HeadTriXz** [comment]
> > Scheduled bans executed too early.
> 
> That's an eloquent way to word instant ban

**Luckily, only one person was affected by this issue.**
